forced_root_block : ""
force_br_newlines : false
convert_newlines_to_brs : false
toolbar:
  - stylesheet | image | link | bold italic underline | bullist numlist | undo redo
plugins:
  - image
  - link
